name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Autobots!!!"
          echo "Roll Out"
          echo "Maximals!!!"
          echo "Maximize"
      - name: Print  goodbye
        run: echo "Done - bye!"
  
